name: Build Fire TV Remote APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk wget

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        buildozer_version: stable

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: FireTV-Remote-APK
        path: bin/*.apk
        if-no-files-found: error

    - name: Display build info
      run: |
        echo "Build completed successfully!"
        ls -lh bin/
        echo "APK ready for download in Actions artifacts"
